-- MySQL Script generated by MySQL Workbench
-- Wed 25 Sep 2019 02:53:43 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetoCloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoCloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoCloud` DEFAULT CHARACTER SET utf8 ;
USE `projetoCloud` ;

-- -----------------------------------------------------
-- Table `projetoCloud`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`user` (
  `iduser` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`post` (
  `idpost` INT NOT NULL,
  `user_iduser_p` INT NULL,
  `titulo` VARCHAR(45) NULL,
  `texto` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idpost`),
  INDEX `iduser_idx` (`user_iduser_p` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`user_iduser_p`)
    REFERENCES `projetoCloud`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`passaro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`passaro` (
  `idpassaro` INT NOT NULL,
  `especie` VARCHAR(45) NULL,
  PRIMARY KEY (`idpassaro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`user_has_passaro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`user_has_passaro` (
  `user_iduser_hp` INT NOT NULL,
  `passaro_idpassaro_hp` INT NOT NULL,
  PRIMARY KEY (`user_iduser_hp`, `passaro_idpassaro_hp`),
  INDEX `fk_user_has_passaro_passaro1_idx` (`passaro_idpassaro_hp` ASC),
  INDEX `fk_user_has_passaro_user1_idx` (`user_iduser_hp` ASC),
  CONSTRAINT `fk_user_has_passaro_user1`
    FOREIGN KEY (`user_iduser_hp`)
    REFERENCES `projetoCloud`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_passaro_passaro1`
    FOREIGN KEY (`passaro_idpassaro_hp`)
    REFERENCES `projetoCloud`.`passaro` (`idpassaro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`log` (
  `idlog` INT NOT NULL,
  `user_iduser_l` INT NULL,
  `os` VARCHAR(45) NULL,
  `browser` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `criado_ts` VARCHAR(45) NULL,
  PRIMARY KEY (`idlog`),
  INDEX `iduser_idx` (`user_iduser_l` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`user_iduser_l`)
    REFERENCES `projetoCloud`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`post_menciona_passaro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`post_menciona_passaro` (
  `post_idpost_mp` INT NOT NULL,
  `passaro_idpassaro_mp` INT NOT NULL,
  PRIMARY KEY (`post_idpost_mp`, `passaro_idpassaro_mp`),
  INDEX `fk_post_has_passaro_passaro1_idx` (`passaro_idpassaro_mp` ASC),
  INDEX `fk_post_has_passaro_post1_idx` (`post_idpost_mp` ASC),
  CONSTRAINT `fk_post_has_passaro_post1`
    FOREIGN KEY (`post_idpost_mp`)
    REFERENCES `projetoCloud`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_passaro_passaro1`
    FOREIGN KEY (`passaro_idpassaro_mp`)
    REFERENCES `projetoCloud`.`passaro` (`idpassaro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoCloud`.`post_menciona_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoCloud`.`post_menciona_user` (
  `post_idpost_mu` INT NOT NULL,
  `user_iduser_mu` INT NOT NULL,
  PRIMARY KEY (`post_idpost_mu`, `user_iduser_mu`),
  INDEX `fk_post_has_user_user1_idx` (`user_iduser_mu` ASC),
  INDEX `fk_post_has_user_post1_idx` (`post_idpost_mu` ASC),
  CONSTRAINT `fk_post_has_user_post1`
    FOREIGN KEY (`post_idpost_mu`)
    REFERENCES `projetoCloud`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_user_user1`
    FOREIGN KEY (`user_iduser_mu`)
    REFERENCES `projetoCloud`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
